name: Build LinkML Artifacts

on:
  push:
    branches:
      - main

jobs:
  gen-artifacts:
    if: github.actor != 'github-actions[bot]'  # skip workflow if triggered by a bot
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run Makefile command
        run: make gen-artifacts

      - name: Commit regenerated artifacts
        run: |
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin main
          git checkout main
          git pull origin main

          git add project/
          git add examples/

          # Commit only if there are staged changes
          if ! git diff --cached --quiet; then
            git commit -m "Regenerate LinkML artifacts"
            git push origin main
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
